### ISSUE TITLE
treesapp create error 

### ISSUE THREAD

**Issue by bharat1912** [hallamlab/TreeSAPP#54]
Hi Connor
I am running TreeSAPP version 0.8.9

I have two questions:
Question 1: I am getting an error building a reference package as a test. I am not sure what the issue is. I have tried different  similarity values and difference sequences (from the same family) but I get the same error. If you could assist, please. 

$ treesapp create --fastx_input lipase.fa --output lip2 --refpkg_name lip2 --cluster --similarity 1 -m prot

##			Creating TreeSAPP reference package			##
Arguments used:
--fastx_input lipase.fa --output lip2 --refpkg_name lip2 --cluster --similarity 0.9 -m prot
Sequence summary:
	Number of sequences: 1
	Longest sequence length: 319
	Shortest sequence length: 319
	Mean sequence length: 319.0
	Median sequence length: 319
Extracting information from headers... done.
Preparing Bio.Entrez for NCBI queries... done.
Retrieving Entrez taxonomy records for each accession... done.
Retrieving NCBI taxonomy IDs for each organism... done.
Preparing Bio.Entrez for NCBI queries... done.
Retrieving lineage information for each taxonomy ID... done.
Preparing Bio.Entrez for NCBI queries... done.
Preparing Bio.Entrez for NCBI queries... done.
ERROR - commands, line 466:
1 sequences post-homology + taxonomy filtering

I have tried different similarity values but get the same error.

Can you assist

Thanks

Bharat
------------------------------------------------------------------------------------
lipase.fa sequence
>sp|P19833.1|LIP1_MORS1 RecName: Full=Lipase 1; AltName: Full=Triacylglycerol lipase
MFIMIKKSELAKAIIVTGALVFSIPTLAEVTLSETTVSSIKSEATVSSTKKALPATPSDCIADSKITAVA
LSDTRDNGPFSIRTKRISRQSAKGFGGGTIHYPTNASGCGLLGAIAVVPGYVSYENSIKWWGPRLASWGF
VVITINTNSIYDDPDSRAAQLNAALDNMIADDTVGSMIDPKRLGAIGWSMGGGGALKLATERSTVRAIMP
LAPYHDKSYGEVKTPTLVIACEDDRIAETKKYANAFYKNAIGPKMKVEVNNGSHFCPSYRFNEILLSKPG
IAWMQRYINNDTRFDKFLCANENYSKSPRISAYDYKDCP

------------------------------------------------------------------------------------------------------------
Question 2. I have an enzyme family of some 20 sequences, all are orthologs and is in a multiple alignment. I wanted to create a build a reference package. I have the taxonomy ids and the accession numbers. Is there another way of creating a reference package. 

Thanks
Bharat

**Comment by cmorganl** [comment]
Hi Bharat,

In the first case, the problem is your input fasta file only contains a single sequence. The minimum number of sequences for TreeSAPP is three so I suggest increasing the number of sequences in your test dataset and retrying.

In the second case, you can
1. use the `--multiple_alignment` flag to skip regenerating the multiple sequence alignment with MAFFT. Although, unless your MSA was manually edited you may as well just regenerate it because it only requires a second.
2. use the `--seqs2lineage` argument to provide a table with the sequence name or accession and the taxonomic lineage information as described [here](https://github.com/hallamlab/TreeSAPP/wiki/Building-reference-packages-with-TreeSAPP#alternative-sources).

Finally, I suggest updating to the latest version (0.9.1) if possible :)

Connor
